"""initial

Revision ID: 5d428f9f359b
Revises: 
Create Date: 2023-09-04 14:56:10.561605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d428f9f359b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_dt', sa.DateTime(), nullable=False),
    sa.Column('end_dt', sa.DateTime(), nullable=False),
    sa.Column('room', sa.String(), server_default='', nullable=True),
    sa.Column('teacher', sa.String(), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons'))
    )
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schools'))
    )
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=False)
    op.create_table('subgroups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subgroups'))
    )
    op.create_index(op.f('ix_subgroups_id'), 'subgroups', ['id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('letter', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_groups_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('lesson_subgroups',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('subgroup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_subgroups_lesson_id_lessons')),
    sa.ForeignKeyConstraint(['subgroup_id'], ['subgroups.id'], name=op.f('fk_lesson_subgroups_subgroup_id_subgroups')),
    sa.PrimaryKeyConstraint('lesson_id', 'subgroup_id', name=op.f('pk_lesson_subgroups'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('subgroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subgroup_id'], ['subgroups.id'], name=op.f('fk_users_subgroup_id_subgroups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('lesson_subgroups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_subgroups_id'), table_name='subgroups')
    op.drop_table('subgroups')
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###
